# Generated by Django 5.1.7 on 2025-03-09 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='date_posted',
            field=models.DateField(blank=True, null=True),
        ),
    ]
