# Generated by Django 5.1.7 on 2025-03-24 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes_api', '0002_quote_date_posted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
    ]
